### ISSUE TITLE
The requested package phplegends/pt-br-validator could not be found in any version

### ISSUE THREAD

**Issue by lsobral** [phplegends/laravel-pt-br-validator#1]
Instalei usando
`composer require phplegends/pt-br-validator`

Mas retornou 
`[InvalidArgumentException]                                                                                            
Could not find package phplegends/pt-br-validator at any version for your minimum-stability (stable). Check the pack age spelling or your minimum-stability`

Poderia me ajudar?

**Comment by brcontainer** [comment]
Se rodar o comando em uma pasta que não seja um projeto Laravel é provável que este erro ocorra mesmo, no entanto também esta ocorrendo um erro ao editar o meu arquivo do meu projeto:
```
{
    "name": "laravel/laravel",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "type": "project",
    "require": {
        "php": ">=5.5.9",
        "laravel/framework": "5.1.*",
        "parse/php-sdk" : "1.1.*",
        "phplegends/pt-br-validator" : "*"
    },
```
Depois rodo o comando `composer update` e aparece o erro:

>   Problem 1
>      - The requested package phplegends/pt-br-validator could not be found in any version, there may be a typo in the package name.

Talvez isto ajude: http://pt.stackoverflow.com/a/102747/3635

**Comment by wallacemaxters** [comment]
Agora,  a biblioteca foi atualizada. Você pode usar a versão 1.0.0.

Para instalação e configuração, favor acompanhar a leitura de README.md.


A configuração do composer.json agora será assim

```json
{
     "phplegends/pt-br-validator" : "1.*"
}
```
