### ISSUE TITLE
Method [validateFormatoCnpj] does not exist.

### ISSUE THREAD

**Issue by ddanborges** [phplegends/laravel-pt-br-validator#3]
Opa, valeu pela iniciativa. Mas estou tendo este erro: 
> Method [validateFormatoCnpj] does not exist.

**Comment by brcontainer** [comment]
@ddanborges o método existe normalmente veja: https://github.com/phplegends/laravel-pt-br-validator/blob/master/src/pt-br-validator/Validator.php#L79 isto me parece um erro de configuração, mas não tenho certeza, forneça um exemplo por favor.

**Comment by ddanborges** [comment]
Sim. Erro de configuração básico, esqueci de adicionar o PHPLegends\PtBrValidator\ValidatorProvider::class no app.php.

Já ia dar close.

Valeu!

**Comment by brcontainer** [comment]
Blz, até mais!
